Neos:
  Neos:
    fusion:
      autoInclude:
        Flowpack.Neos.WhatsNewDashboard: true
    Ui:
      resources:
        javascript:
          Flowpack.Neos.WhatsNewDashboard:BackendModal:
            resource: 'resource://Flowpack.Neos.WhatsNewDashboard/Public/BackendModal.js'
        stylesheets:
          Flowpack.Neos.WhatsNewDashboard:BackendModal:
            resource: 'resource://Flowpack.Neos.WhatsNewDashboard/Public/main.css'
